### PR TITLE
chore: add ca-certificates deps in the image

### PR DESCRIPTION
**Pull request by Peefy**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y 

re https://github.com/crossplane-contrib/function-kcl/issues/191

+ chore: add ca-certificates deps in the image

### CODE REVIEW

**Review by zong-zhe — APPROVED** [review]
LGTM

**Comment by spastorclovr** [comment]
Hello, 
When do you think this patch will be part of a a release? This is actually blocking as, since this morning at least, kcl modules cannot be downloaded from `ghcr.io` and I believe this is related to the certificates not being up-to-date.

> failed to resolve 1.31.2: Get "https://ghcr.io/v2/kcl-lang/k8s/manifests/1.31.2": tls: failed to verify certificate: x509: certificate signed by unknown authority

Thx!

**Comment by spastorclovr** [comment]
Thx for your reply @Peefy . Unless I am mistaken, the image does not seem to be pushed/available yet.

>  2024-11-21T07:46:15+01:00	DEBUG	Image not found, pulling	{"image": "xpkg.upbound.io/crossplane-contrib/function-kcl:v0.10.10"}
crossplane: error: cannot render composite resource: cannot start function runtimes: cannot start Function "kcl-function": cannot pull Docker image "xpkg.upbound.io/crossplane-contrib/function-kcl:v0.10.10": Error response from daemon: manifest for xpkg.upbound.io/crossplane-contrib/function-kcl:v0.10.10 not found: manifest unknown: manifest unknown

**Comment by spastorclovr** [comment]
Thx a bunch @Peefy . It now works perfectly with latest crossplane-contrib/function-kcl:v0.10.10

:+1:

**Pull request merged**
